In [1]:
### import libraries
import argparse
import json
import requests
import re
from collections import defaultdict
import pandas as pd
import numpy as np
from ast import literal_eval

In [2]:
### credentials (expires Aug 19 '24')
# go to graphQL explorer - https://developers.facebook.com/tools/explorer/
# copy the token
# debug & extend the token - https://developers.facebook.com/tools/debug/accesstoken/
ACCESS_TOKEN = "TOKEN"

In [3]:
### functions

def calculate_impressions_midpoint(data):
    """Calculate impressions midpoint"""
    # Convert from a string of characters into an integer
    upper_bound = int(data["impressions"]["upper_bound"])
    lower_bound = int(data["impressions"]["lower_bound"])

    return round((upper_bound + lower_bound) / 2)

def calculate_impressions_by_region(data, impressions):
    """Calculate impressions by regions"""
    # Create a new dict to contain the results
    result = {}

    # Loop through each region and calculate the impressions
    for chunk in data["delivery_by_region"]:
        result[chunk["region"]] = round(impressions * float(chunk["percentage"]))

    return result

def calculate_impressions_by_gender(data, impressions):
    """Calculates impressions by gender"""
    # Create a new dict to contain the results. The categories are pre-populated with 0s.
    results = {"male": 0, "female": 0, "unknown": 0}

    # Loop through demographic data
    for d in data["demographic_distribution"]:
        # Let's break this expression down:
        # 1. result[d["gender"]] looks for the key in the result dict that matches d["gender"]
        # 2. += is a short hand operator for addition and assignment. e.g. foo +=1 is the same
        #    as foo = foo + 1
        # 3. float(d["percentage"]) converts the JSON data into a decimal number (programmers
        #    call those floats because the decimal can move around).
        # 4. round(impressions * float(d["percentage"])) multiplies the percentage by the
        #    impressions and rounds up to the nearest integer
        results[d["gender"]] += round(impressions * float(d["percentage"]))

    return results

def calculate_impressions_by_age(data, impressions):
    """Calculate impressions by age"""
    # Create a new default dict to contain the results. The default dict makes any new element
    # default to a value specified by the user. In our case we're defaulting to an integer 0.
    # int is actually a function that retuns 0 when called with no arguments
    results = defaultdict(int)

    # Loop through the demographic data and add up the impressions
    for d in data["demographic_distribution"]:
        # Let's break this expression down:
        # 1. result[d["age"]] looks for the key in the result dict that matches d["age"]. If
        #    there is no key that matches d["age"] the default dict will make one with the value
        #    of int(), which is always 0.
        # 2. += is a short hand operator for addition and assignment. e.g. foo +=1 is the same
        #    as foo = foo + 1
        # 3. float(d["percentage"]) converts the JSON data into a decimal number (programmers
        #    call those floats because the decimal can move around).
        # 4. round(impressions * float(d["percentage"])) multiplies the percentage by the
        #    impressions and rounds up to the nearest integer
        results[d["age"]] += round(impressions * float(d["percentage"]))

    return results

In [3]:
### list of page IDs

idList = ['106039214814684', #affordable energy coalition
'102281724942742',
'738063612887865',
'341751646428117',
'591566840920364',
'105502284969626',
'49560242814', # not showing up???
'101691091213750',
# '113891694102', removed Energy Citizens
'292970844058835',
'100801038449520',
'108095672108380',
'111394533709201',
'107500120800840',
'101242238726088',
'237209147160346',
'110124925319299',
'396341921119746',
'108203188195224',
'106656845034469',
'47710973068',
'482100658584410']

In [5]:
"""Entrypoint of the program"""

# Store the paginated data in here
data = []

# create dataframe
df = pd.DataFrame()

# for each item in the list, store their data in the pandas dataframe

# This might work for our request
for i in idList:
    print(i)
    response = requests.get("https://graph.facebook.com/v5.0/ads_archive", params={
    "access_token": ACCESS_TOKEN,
    "ad_type": "POLITICAL_AND_ISSUE_ADS",
    "ad_active_status": "ALL",
    "search_page_ids": i,
    "ad_reached_countries": ["US"],
    "ad_delivery_date_min": "2018-05-07",
    "ad_delivery_date_max": "2024-06-14",
    "fields": "id, ad_delivery_start_time, ad_delivery_stop_time, ad_snapshot_url, bylines, delivery_by_region, demographic_distribution, impressions, publisher_platforms, spend, ad_creative_bodies, ad_creative_link_captions, ad_creative_link_descriptions, ad_creative_link_titles, page_name, page_id"
})
    # Get the json document and pull out the next link and the data
    json = response.json()
    
    try:
        next_link = json['paging']['next']
        data = data + json['data']
    except KeyError:
        continue

    while next_link:
      print('.', end='')
      response = requests.get(next_link)
      json = response.json()
      if 'paging' not in json:
        break
      next_link = json['paging']['next']
      data = data + json['data']
    print('\n')

    # append data to dataframe
    res = pd.json_normalize(data)
    df = pd.concat([df, res], ignore_index=True)

106039214814684
.....

102281724942742
.........................................................................................................................................................

738063612887865
................................................................................................................................

341751646428117
..

591566840920364
............................................

105502284969626
..

49560242814
............................................................................................

101691091213750
.........................................................................................

292970844058835
.

100801038449520
..................................................................................

108095672108380
..

111394533709201
.

107500120800840
...............

101242238726088
..............

237209147160346
..................

110124925319299
..

396341921119746
......

108203188195224
.........

106656845034469
............

47710973068
.....................................................................................................................................................

482100658584410
...............................................

### Clean & Export Data

### For Summary Table

In [22]:
# drop duplicate ads (based on id)
df = df.drop_duplicates(subset="id")

In [6]:
# check NaNs:
# df['ad_delivery_stop_time'][df['ad_delivery_stop_time'].isna()]

# fill NaN with '999'
df['ad_delivery_stop_time'] = df['ad_delivery_stop_time'].fillna('999')

In [7]:
# create 'ad start month' and 'ad start year' column
df['ad_start_month'] = df['ad_delivery_start_time'].str.split('-').str[1].astype(int)
df['ad_start_year'] = df['ad_delivery_start_time'].str.split('-').str[0].astype(int)

In [8]:
# convert string to integer
df['spend.lower_bound'] = df['spend.lower_bound'].astype('int')
df['spend.upper_bound'] = df['spend.upper_bound'].astype('int').round(-2)

In [9]:
# title case for bylines column
df['bylines'] = df['bylines'].str.title()

In [10]:
# replace page_name: 'Natural Gas: Limitless Opportunity' with 'Save Our Stoves' and 'Cooperative Action Network' with 'Voices for Cooperative Power'

df['page_name'] = df['page_name'].replace({'Natural Gas: Limitless Opportunity':'Save Our Stoves', 'Cooperative Action Network':'Voices for Cooperative Power'})

In [38]:
resjson = df[['page_name', 'id', 'spend.lower_bound', 'spend.upper_bound']].groupby('page_name').agg({'id':'count', 'spend.lower_bound': 'sum', 'spend.upper_bound': 'sum'}).reset_index().rename(columns={'page_name':'name', 'id':'ads', 'spend.lower_bound': 'lowerAmount', 'spend.upper_bound':'upperAmount'}).sort_values(by="upperAmount", ascending=False).reset_index(drop=True)

In [55]:
df[['page_name', 'id', 'spend.lower_bound', 'spend.upper_bound']].groupby('page_name').agg({'id':'count', 'spend.lower_bound': 'sum', 'spend.upper_bound': 'sum'}).reset_index().rename(columns={'page_name':'name', 'id':'ads', 'spend.lower_bound': 'lowerAmount', 'spend.upper_bound':'upperAmount'}).sort_values(by="upperAmount", ascending=False).reset_index(drop=True)

                                          name   ads  lowerAmount  upperAmount
0                 Voices for Cooperative Power  3705      1842300      2592400
1     Natural Allies for a Clean Energy Future  2033       868100      1235000
2                     Consumer Energy Alliance  2276       584900       929000
3                     The Empowerment Alliance  2205       590000       924000
4                  Alliance for Michigan Power  3180       306900       661500
5             Affordable Energy for New Jersey  3811       149400       539300
6       Citizens Energizing Michigan's Economy  1100       237300       378700
7                       Seniors Across America   223       252900       330200
8                           Power for Tomorrow   343       231600       305800
9                            Smarter NY Energy   300       190600       257200
10             Partnership for Energy Progress   357       186800       256200
11                         We Stand For Energy  1151       102300       227400
12           New Yorkers For Affordable Energy    16        79300        95000
13                 Affordable Energy Coalition   117        45200        65300
14                             Save Our Stoves    26        48000        57700
15                         Real Coalition Iowa   446         3700        48700
16                     SC Clean Energy For All   132         6800        20400
17  Californians for Balanced Energy Solutions    49        12500        19000
18     Coalition for Cleaner Affordable Energy    34         7800        12400
19         Natural Gas for the Next Generation    34            0         3400
20                          Jobkeeper Alliance     1         1500         2000

In [25]:
# export data
resjson.to_json('../data/summary-062024.json', orient = 'records')

### For Individual Tables

In [47]:
# unpack the dataset to access region data
result = pd.concat([df.explode('delivery_by_region').drop(['delivery_by_region'], axis=1),
           df.explode('delivery_by_region')['delivery_by_region'].apply(pd.Series)],
          axis=1)

In [49]:
# remove duplicates
resultClean = result.drop_duplicates(subset="id")

In [50]:
# convert to float type 
resultClean['percentage'] = resultClean['percentage'].astype(float)

/var/folders/hl/5vgjw5l925q71n0d_fv_g5rh0000gn/T/ipykernel_99995/2210950792.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resultClean['percentage'] = resultClean['percentage'].astype(float)

In [51]:
# calculate lower & upper amount spent per region
resultClean['lowerAmount'] = resultClean['percentage'] * resultClean['spend.lower_bound']
resultClean['upperAmount'] = resultClean['percentage'] * resultClean['spend.upper_bound']

/var/folders/hl/5vgjw5l925q71n0d_fv_g5rh0000gn/T/ipykernel_99995/197889030.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resultClean['lowerAmount'] = resultClean['percentage'] * resultClean['spend.lower_bound']
/var/folders/hl/5vgjw5l925q71n0d_fv_g5rh0000gn/T/ipykernel_99995/197889030.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resultClean['upperAmount'] = resultClean['percentage'] * resultClean['spend.upper_bound']

In [56]:
# view data
resultClean[['page_name', 'region', 'lowerAmount', 'upperAmount']].groupby(['page_name', 'region']).sum(['lowerAmount', 'upperAmount']).sort_values(by="upperAmount", ascending=False).reset_index().rename(columns={'page_name':'name'})

,name,region,lowerAmount,upperAmount
0,Alliance for Michigan Power,Michigan,243199.5972,480198.9368
1,Affordable Energy for New Jersey,New Jersey,117799.1575,417769.7286
2,Consumer Energy Alliance,Minnesota,313100.0150,402292.8355
3,Citizens Energizing Michigan's Economy,Michigan,173898.4945,276697.6203
4,Natural Allies for a Clean Energy Future,"Washington, District of Columbia",204761.3832,272854.8432
...,...,...,...,...
505,Citizens Energizing Michigan's Economy,Texas,0.0000,0.0085
506,Citizens Energizing Michigan's Economy,Oklahoma,0.0041,0.0082
507,New Yorkers For Affordable Energy,Georgia,0.0070,0.0080
508,Consumer Energy Alliance,Ontario,0.0034,0.0068
509,We Stand For Energy,Michoacán de Ocampo,0.0042,0.0049

In [58]:
# if the percentage amount is less 10%, don't include it
# resultClean = result.query("percentage >.10")

In [59]:
# export data
resultClean[['page_name', 'region', 'lowerAmount', 'upperAmount', 'percentage']].query("percentage > 0.10").groupby(['page_name', 'region']).sum(['lowerAmount', 'upperAmount']).reset_index().rename(columns={'page_name':'name'}).to_json('../data/individual-062024.json', orient = 'records')

### Experimentation

In [351]:
# import all data files
df0 = pd.read_csv('../data/batch0-front-group-ads-040824.csv')
df1 = pd.read_csv('../data/batch1-front-group-ads-040824.csv')
df2 = pd.read_csv('../data/batch2-front-group-ads-040824.csv')

In [378]:
# merge files
df = pd.concat([df0, df1, df2], axis=0).drop('Unnamed: 0', axis=1).reset_index(drop=True)

In [373]:
# read 'delivery_by_region' as JSON

df['delivery_by_region'] = [re.sub(r"(?<!\\)'", '"', str(x)) for x in df['delivery_by_region']]

# fill NANs
# df['delivery_by_region'] = df['delivery_by_region'].fillna(r"""[{'percentage': '0.00', 'region': 'none'}]""")

# replace single quotes to double quotes to turn into JSON
# df['delivery_by_region'] = df['delivery_by_region'].str.replace("'", '"')
# df['delivery_by_region'] = df['delivery_by_region'].str.replace("\'region'", '\"region"')

# clean data -

# convert to json
# df['delivery_by_region'].apply(json.loads)


# jsonstring = r"""[{"percentage": "0.00", "region": "none"}]"""

# replace single quotes to double quotes to turn into JSON
# df['delivery_by_region'] = df['delivery_by_region'].str.replace("\'", "\"")

# df['delivery_by_region'].apply(lambda x: json.loads(x))
# df['delivery_by_region'].apply(json.loads)

In [383]:
# pd.concat(
# df.explode("delivery_by_region")["delivery_by_region"].apply(pd.Series)
# df['delivery_by_region'].explode().to_dict()).T

# df["delivery_by_region"][0]
# df["delivery_by_region"][7159]
# df["delivery_by_region"][7150:7160].apply(json.loads)

re.sub(r"(?<!\\)'", '"', df["delivery_by_region"][7159])

'[{"percentage": "8.0E-6", "region": "Zawiya District"}, {"percentage": "2.3E-5", "region": "Bahia"}, {"percentage": "3.0E-5", "region": "Edo State"}, {"percentage": "8.0E-6", "region": "Adamawa State"}, {"percentage": "8.0E-6", "region": "West Pomeranian Voivodeship"}, {"percentage": "8.0E-6", "region": "Opole Voivodeship"}, {"percentage": "8.0E-6", "region": "Lublin Voivodeship"}, {"percentage": "8.0E-6", "region": "Lower Silesian Voivodeship"}, {"percentage": "8.0E-6", "region": "New South Wales"}, {"percentage": "1.5E-5", "region": "Santa Catarina"}, {"percentage": "3.8E-5", "region": "Minas Gerais"}, {"percentage": "8.0E-6", "region": "Ahmadi Governorate"}, {"percentage": "1.5E-5", "region": "Coast Province"}, {"percentage": "8.0E-6", "region": "Autonomous Region in Muslim Mindanao"}, {"percentage": "2.3E-5", "region": "Caraga"}, {"percentage": "3.0E-5", "region": "Central Luzon"}, {"percentage": "1.5E-5", "region": "Ilocos Region"}, {"percentage": "8.0E-6", "region": "Upper Austria"}, {"percentage": "3.8E-5", "region": "Central Kalimantan"}, {"percentage": "8.0E-6", "region": "Special Region of Yogyakarta"}, {"percentage": "8.0E-6", "region": "San Martín Region"}, {"percentage": "8.0E-6", "region": "Callao"}, {"percentage": "8.0E-6", "region": "Amazonas Region"}, {"percentage": "6.8E-5", "region": "Abia State"}, {"percentage": "8.0E-6", "region": "Rabat-Salé-Zemmour-Zaer"}, {"percentage": "8.0E-6", "region": "Samut Sakhon"}, {"percentage": "8.0E-6", "region": "West Bengal"}, {"percentage": "8.0E-6", "region": "Maritime Region"}, {"percentage": "8.0E-6", "region": "Selangor"}, {"percentage": "8.0E-6", "region": "Littoral Department"}, {"percentage": "1.5E-5", "region": "Beirut Governorate"}, {"percentage": "8.0E-6", "region": "Kigali"}, {"percentage": "8.0E-6", "region": "Anosy Region"}, {"percentage": "8.0E-6", "region": "Haute Matsiatra"}, {"percentage": "2.3E-5", "region": "Baku"}, {"percentage": "8.0E-6", "region": "Abidjan"}, {"percentage": "1.5E-5", "region": "Odisha"}, {"percentage": "8.0E-6", "region": "Argeș County"}, {"percentage": "8.0E-6", "region": "Mbarara District"}, {"percentage": "8.0E-6", "region": "Lumbini Zone"}, {"percentage": "2.3E-5", "region": "Narayani Zone"}, {"percentage": "8.0E-6", "region": "Cherkasy Oblast"}, {"percentage": "8.0E-6", "region": "Quảng Nam Province"}, {"percentage": "8.0E-6", "region": "Central Department"}, {"percentage": "1.5E-5", "region": "Gharbia Governorate"}, {"percentage": "1.5E-5", "region": "Al Sharqia Governorate"}, {"percentage": "8.0E-6", "region": "Maramureș County"}, {"percentage": "8.0E-6", "region": "Constanța County"}, {"percentage": "8.0E-6", "region": "O"Higgins Region"}, {"percentage": "1.5E-5", "region": "Nakhon Ratchasima"}, {"percentage": "8.0E-6", "region": "Katanga"}, {"percentage": "1.5E-5", "region": "Manipur"}, {"percentage": "8.0E-6", "region": "Sana"a Governorate"}, {"percentage": "8.0E-6", "region": "Campania"}, {"percentage": "8.0E-6", "region": "Calabria"}, {"percentage": "8.0E-6", "region": "Central Division"}, {"percentage": "8.0E-6", "region": "Sava Region"}, {"percentage": "1.5E-5", "region": "Oromia Region"}, {"percentage": "1.5E-5", "region": "Dar es Salaam"}, {"percentage": "2.3E-5", "region": "Uttarakhand"}, {"percentage": "8.0E-6", "region": "Puducherry"}, {"percentage": "2.3E-5", "region": "Jammu and Kashmir"}, {"percentage": "8.0E-6", "region": "Atlantique Department"}, {"percentage": "8.0E-6", "region": "Haryana"}, {"percentage": "8.0E-6", "region": "Andhra Pradesh"}, {"percentage": "1.5E-5", "region": "Janakpur Zone"}, {"percentage": "8.0E-6", "region": "Mechi Zone"}, {"percentage": "1.5E-5", "region": "Kosi Zone"}, {"percentage": "8.0E-6", "region": "Riga Planning Region"}, {"percentage": "8.0E-6", "region": "Gozo"}, {"percentage": "1.5E-5", "region": "Western Region"}, {"percentage": "2.3E-5", "region": "Northern Region"}, {"percentage": "1.5E-5", "region": "Eastern Region"}, {"percentage": "2.3E-5", "region": "Demerara-Mahaica"}, {"percentage": "8.0E-6", "region": "Alibori Department"}, {"percentage": "8.0E-6", "region": "Sakon Nakhon"}, {"percentage": "4.5E-5", "region": "Limpopo"}, {"percentage": "8.0E-6", "region": "Nakhon Sawan"}, {"percentage": "8.0E-6", "region": "Mae Hong Son"}, {"percentage": "2.3E-5", "region": "Wales"}, {"percentage": "8.0E-6", "region": "Amman Governorate"}, {"percentage": "8.0E-6", "region": "Wallonia"}, {"percentage": "8.0E-6", "region": "Quebec"}, {"percentage": "8.0E-6", "region": "Dubai"}, {"percentage": "8.0E-6", "region": "Dalarna County"}, {"percentage": "8.0E-6", "region": "Sint Maarten"}, {"percentage": "8.0E-6", "region": "N"Djamena"}, {"percentage": "8.0E-6", "region": "Ulan Bator"}, {"percentage": "2.3E-5", "region": "Banaadir"}, {"percentage": "8.0E-6", "region": "Oregon"}, {"percentage": "3.8E-5", "region": "Nebraska"}, {"percentage": "1.5E-5", "region": "Kindia Region"}, {"percentage": "1.5E-5", "region": "Conakry"}, {"percentage": "2.3E-5", "region": "Montserrado County"}, {"percentage": "8.0E-6", "region": "Sangha Department"}, {"percentage": "8.0E-6", "region": "Paramaribo District"}, {"percentage": "8.0E-6", "region": "Nord-Kivu"}, {"percentage": "8.0E-6", "region": "Tamaulipas"}, {"percentage": "8.0E-6", "region": "Chiapas"}, {"percentage": "8.0E-6", "region": "Hela Province"}, {"percentage": "6.8E-5", "region": "Ashanti Region"}, {"percentage": "9.0E-5", "region": "Georgia"}, {"percentage": "0.00027", "region": "Texas"}, {"percentage": "0.00015", "region": "Tennessee"}, {"percentage": "0.000143", "region": "Pennsylvania"}, {"percentage": "0.000188", "region": "New York"}, {"percentage": "9.0E-5", "region": "New Jersey"}, {"percentage": "9.0E-5", "region": "Minnesota"}, {"percentage": "9.0E-5", "region": "Michigan"}, {"percentage": "0.000113", "region": "Massachusetts"}, {"percentage": "0.00012", "region": "Louisiana"}, {"percentage": "0.989469", "region": "Florida"}, {"percentage": "1.5E-5", "region": "Washington"}, {"percentage": "1.5E-5", "region": "Delaware"}, {"percentage": "8.3E-5", "region": "Connecticut"}, {"percentage": "9.8E-5", "region": "California"}, {"percentage": "5.3E-5", "region": "Alabama"}, {"percentage": "8.0E-6", "region": "Lilongwe District"}, {"percentage": "8.0E-6", "region": "East Berbice-Corentyne"}, {"percentage": "8.0E-6", "region": "Tuscany"}, {"percentage": "8.0E-6", "region": "Boeny"}, {"percentage": "0.000128", "region": "Analamanga"}, {"percentage": "3.8E-5", "region": "Bihar"}, {"percentage": "1.5E-5", "region": "Virginia"}, {"percentage": "8.0E-6", "region": "Kosovo"}, {"percentage": "6.8E-5", "region": "Kampala District"}, {"percentage": "3.0E-5", "region": "Soccsksargen"}, {"percentage": "0.000158", "region": "Greater Accra Region"}, {"percentage": "1.5E-5", "region": "Nasarawa State"}, {"percentage": "3.8E-5", "region": "Enugu State"}, {"percentage": "3.0E-5", "region": "Osun State"}, {"percentage": "1.5E-5", "region": "Kogi State"}, {"percentage": "2.3E-5", "region": "Oyo State"}, {"percentage": "8.0E-6", "region": "Borno State"}, {"percentage": "9.8E-5", "region": "Kaduna State"}, {"percentage": "0.000203", "region": "Lagos State"}, {"percentage": "6.0E-5", "region": "South Sumatra"}, {"percentage": "4.5E-5", "region": "Eastern Cape"}, {"percentage": "3.8E-5", "region": "West Nusa Tenggara"}, {"percentage": "5.3E-5", "region": "Lampung"}, {"percentage": "0.000143", "region": "East Java"}, {"percentage": "0.000135", "region": "Central Java"}, {"percentage": "0.00045", "region": "England"}, {"percentage": "8.0E-6", "region": "Jerusalem"}, {"percentage": "3.0E-5", "region": "Ontario"}, {"percentage": "8.0E-6", "region": "Nova Scotia"}, {"percentage": "8.0E-6", "region": "Şanlıurfa Province"}, {"percentage": "6.8E-5", "region": "Gauteng"}, {"percentage": "3.0E-5", "region": "Assam"}, {"percentage": "8.0E-6", "region": "Muharraq Governorate"}, {"percentage": "8.0E-6", "region": "Maseru District"}, {"percentage": "8.0E-6", "region": "Fujairah"}, {"percentage": "8.0E-6", "region": "Piauí"}, {"percentage": "8.0E-6", "region": "Maranhão"}, {"percentage": "1.5E-5", "region": "Ceará"}, {"percentage": "8.0E-6", "region": "Hong Kong"}, {"percentage": "1.5E-5", "region": "Southeast Sulawesi"}, {"percentage": "8.0E-6", "region": "Jambi"}, {"percentage": "8.0E-6", "region": "Flemish Region"}, {"percentage": "8.0E-6", "region": "Tel Aviv"}, {"percentage": "8.0E-6", "region": "Manitoba"}, {"percentage": "8.0E-6", "region": "Castilla y Leon"}, {"percentage": "1.5E-5", "region": "Pernambuco"}, {"percentage": "8.0E-6", "region": "Comunidad de Madrid"}, {"percentage": "6.8E-5", "region": "KwaZulu-Natal"}, {"percentage": "8.0E-6", "region": "Honiara"}, {"percentage": "8.0E-6", "region": "North Dakota"}, {"percentage": "3.0E-5", "region": "New Mexico"}, {"percentage": "1.5E-5", "region": "Bujumbura"}, {"percentage": "8.0E-6", "region": "Boké Region"}, {"percentage": "8.0E-6", "region": "Pointe-Noire"}, {"percentage": "8.0E-6", "region": "Southern Province"}, {"percentage": "1.5E-5", "region": "Nouakchott"}, {"percentage": "8.0E-6", "region": "Roraima"}, {"percentage": "2.3E-5", "region": "Victoria"}, {"percentage": "8.3E-5", "region": "Nairobi"}, {"percentage": "8.0E-6", "region": "Muscat Governorate"}, {"percentage": "2.3E-5", "region": "Queensland"}, {"percentage": "8.0E-6", "region": "Comunidad Valenciana"}, {"percentage": "7.5E-5", "region": "Wisconsin"}, {"percentage": "9.0E-5", "region": "Ohio"}, {"percentage": "6.0E-5", "region": "New Hampshire"}, {"percentage": "2.3E-5", "region": "Iowa"}, {"percentage": "0.00012", "region": "Indiana"}, {"percentage": "0.000188", "region": "Illinois"}, {"percentage": "2.3E-5", "region": "Gandaki Zone"}, {"percentage": "8.0E-6", "region": "Sumy Oblast"}, {"percentage": "1.5E-5", "region": "Ondo State"}, {"percentage": "8.0E-6", "region": "Dnipropetrovsk Oblast"}, {"percentage": "8.0E-6", "region": "Alsace"}, {"percentage": "2.3E-5", "region": "Île-de-France"}, {"percentage": "8.0E-6", "region": "West Bank"}, {"percentage": "8.0E-6", "region": "Caaguazú Department"}, {"percentage": "8.0E-6", "region": "Beheira Governorate"}, {"percentage": "8.0E-6", "region": "La Paz Department"}, {"percentage": "8.0E-6", "region": "Iași County"}, {"percentage": "8.0E-6", "region": "Szabolcs-Szatmár-Bereg County"}, {"percentage": "8.0E-6", "region": "Western Province"}, {"percentage": "1.5E-5", "region": "Central Region"}, {"percentage": "8.0E-6", "region": "Hanoi"}, {"percentage": "8.0E-6", "region": "Saint Andrew Parish"}, {"percentage": "2.3E-5", "region": "Gujarat"}, {"percentage": "1.5E-5", "region": "Chhattisgarh"}, {"percentage": "6.0E-5", "region": "Uttar Pradesh"}, {"percentage": "3.8E-5", "region": "Madhya Pradesh"}, {"percentage": "2.3E-5", "region": "Tamil Nadu"}, {"percentage": "2.3E-5", "region": "Rajasthan"}, {"percentage": "1.5E-5", "region": "Karnataka"}, {"percentage": "2.3E-5", "region": "Maharashtra"}, {"percentage": "1.5E-5", "region": "Kerala"}, {"percentage": "2.3E-5", "region": "Himachal Pradesh"}, {"percentage": "1.5E-5", "region": "Delhi"}, {"percentage": "8.0E-6", "region": "Telangana"}, {"percentage": "1.5E-5", "region": "Dakar Region"}, {"percentage": "6.8E-5", "region": "Bagmati Zone"}, {"percentage": "8.0E-6", "region": "Sagarmatha Zone"}, {"percentage": "8.0E-6", "region": "Ismailia Governorate"}, {"percentage": "8.0E-6", "region": "Asyut Governorate"}, {"percentage": "8.0E-6", "region": "Aswan Governorate"}, {"percentage": "8.0E-6", "region": "Neamț County"}, {"percentage": "8.0E-6", "region": "Caraș-Severin County"}, {"percentage": "8.0E-6", "region": "Oriental"}, {"percentage": "8.0E-6", "region": "Marrakesh-Tensift-El Haouz"}, {"percentage": "1.5E-5", "region": "Jharkhand"}, {"percentage": "8.0E-6", "region": "Lagunes District"}, {"percentage": "8.0E-6", "region": "Viseu District"}, {"percentage": "1.5E-5", "region": "Puebla"}, {"percentage": "3.8E-5", "region": "Western Area"}, {"percentage": "8.0E-6", "region": "Taranaki"}, {"percentage": "8.0E-6", "region": "Groningen"}, {"percentage": "8.0E-6", "region": "Vientiane Prefecture"}, {"percentage": "8.0E-6", "region": "Salavan Province"}, {"percentage": "8.0E-6", "region": "Phongsaly Province"}, {"percentage": "3.0E-5", "region": "Port Moresby"}, {"percentage": "6.0E-5", "region": "Kinshasa"}, {"percentage": "8.0E-6", "region": "Tlaxcala"}, {"percentage": "8.0E-6", "region": "Durango"}, {"percentage": "2.3E-5", "region": "Addis Ababa"}, {"percentage": "1.5E-5", "region": "Huíla Province"}, {"percentage": "3.8E-5", "region": "Luanda Province"}, {"percentage": "3.0E-5", "region": "Bamako"}, {"percentage": "8.0E-6", "region": "Tete Province"}, {"percentage": "1.5E-5", "region": "Blantyre District"}, {"percentage": "8.0E-6", "region": "Lusaka Province"}, {"percentage": "8.0E-6", "region": "Drochia District"}, {"percentage": "8.0E-6", "region": "Sofia Region"}, {"percentage": "1.5E-5", "region": "Diana Region"}, {"percentage": "8.0E-6", "region": "Atsimo-Andrefana"}, {"percentage": "8.0E-6", "region": "North Eastern Province"}, {"percentage": "2.3E-5", "region": "Papua (province)"}, {"percentage": "3.0E-5", "region": "Colorado"}, {"percentage": "8.0E-6", "region": "North Maluku"}, {"percentage": "8.0E-6", "region": "Iganga District"}, {"percentage": "8.0E-6", "region": "Bourgogne"}, {"percentage": "8.0E-6", "region": "Flacq District"}, {"percentage": "8.0E-6", "region": "Jász-Nagykun-Szolnok County"}, {"percentage": "8.0E-6", "region": "Luxembourg District"}, {"percentage": "8.0E-6", "region": "Azores"}, {"percentage": "8.0E-6", "region": "Lesser Poland Voivodeship"}, {"percentage": "8.0E-6", "region": "Paraná"}, {"percentage": "8.0E-6", "region": "Federal District"}, {"percentage": "8.0E-6", "region": "Loreto Region"}, {"percentage": "8.0E-6", "region": "Khomas Region"}, {"percentage": "8.0E-6", "region": "Phetchaburi"}, {"percentage": "8.0E-6", "region": "Capital Region of Denmark"}, {"percentage": "8.0E-6", "region": "Saskatchewan"}, {"percentage": "8.0E-6", "region": "Stockholm County"}, {"percentage": "8.0E-6", "region": "Kalmar County"}, {"percentage": "8.0E-6", "region": "Free State"}, {"percentage": "1.5E-5", "region": "Wyoming"}, {"percentage": "8.0E-6", "region": "Vermont"}, {"percentage": "8.0E-6", "region": "Western Highlands Province"}, {"percentage": "8.0E-6", "region": "Oaxaca"}, {"percentage": "8.0E-6", "region": "Dire Dawa"}, {"percentage": "8.0E-6", "region": "Uíge Province"}, {"percentage": "8.0E-6", "region": "Réunion"}, {"percentage": "8.0E-6", "region": "Jinja District"}, {"percentage": "8.0E-6", "region": "Riyadh Region"}, {"percentage": "8.0E-6", "region": "Hiran"}, {"percentage": "8.0E-6", "region": "Punjab"}, {"percentage": "8.0E-6", "region": "Nevada"}, {"percentage": "8.0E-6", "region": "Sud-Kivu"}, {"percentage": "1.5E-5", "region": "Orientale"}, {"percentage": "8.0E-6", "region": "State of Mexico"}, {"percentage": "8.0E-6", "region": "South Kazakhstan Region"}, {"percentage": "8.0E-6", "region": "Mwanza"}, {"percentage": "8.0E-6", "region": "Rivière du Rempart District"}, {"percentage": "8.0E-6", "region": "Gaziantep Province"}, {"percentage": "8.0E-6", "region": "Republika Srpska"}, {"percentage": "8.0E-6", "region": "Carolina"}, {"percentage": "8.0E-6", "region": "Prahova County"}, {"percentage": "8.0E-6", "region": "Central Province"}, {"percentage": "8.0E-6", "region": "Kuyavian-Pomeranian Voivodeship"}, {"percentage": "8.0E-6", "region": "Espírito Santo"}, {"percentage": "8.0E-6", "region": "Cordillera Administrative Region"}, {"percentage": "1.5E-5", "region": "Lima Region"}, {"percentage": "8.0E-6", "region": "Nakhon Phanom"}, {"percentage": "8.0E-6", "region": "Buenos Aires"}, {"percentage": "0.000113", "region": "Arkansas"}, {"percentage": "3.8E-5", "region": "Kansas"}, {"percentage": "8.0E-6", "region": "Siliana Governorate"}, {"percentage": "8.0E-6", "region": "Pomeranian Voivodeship"}, {"percentage": "5.3E-5", "region": "Kwara State"}, {"percentage": "8.3E-5", "region": "Kano State"}, {"percentage": "8.0E-6", "region": "Benué State"}, {"percentage": "2.3E-5", "region": "Anambra State"}, {"percentage": "1.5E-5", "region": "Cross River State"}, {"percentage": "2.3E-5", "region": "Akwa Ibom State"}, {"percentage": "3.0E-5", "region": "Ogun State"}, {"percentage": "7.5E-5", "region": "Federal Capital Territory"}, {"percentage": "8.0E-6", "region": "Taoyuan City"}, {"percentage": "6.8E-5", "region": "São Paulo (state)"}, {"percentage": "1.5E-5", "region": "Delta State"}, {"percentage": "3.0E-5", "region": "Rio Grande do Sul"}, {"percentage": "1.5E-5", "region": "Paraíba"}, {"percentage": "3.0E-5", "region": "Northern Mindanao"}, {"percentage": "3.8E-5", "region": "Eastern Visayas"}, {"percentage": "5.3E-5", "region": "Central Visayas"}, {"percentage": "4.5E-5", "region": "Western Visayas"}, {"percentage": "3.8E-5", "region": "Bicol Region"}, {"percentage": "9.8E-5", "region": "Calabarzon"}, {"percentage": "3.0E-5", "region": "Cagayan Valley"}, {"percentage": "2.3E-5", "region": "Metro Manila"}, {"percentage": "4.5E-5", "region": "Niger State"}, {"percentage": "1.5E-5", "region": "Jigawa State"}, {"percentage": "5.3E-5", "region": "Davao Region"}, {"percentage": "8.0E-6", "region": "Santa Elena Province"}, {"percentage": "8.0E-6", "region": "Alexandria Governorate"}, {"percentage": "1.5E-5", "region": "Cairo Governorate"}, {"percentage": "8.0E-6", "region": "La Libertad Department"}, {"percentage": "8.0E-6", "region": "Santa Cruz Department"}, {"percentage": "8.0E-6", "region": "Timiș County"}, {"percentage": "8.0E-6", "region": "Suceava County"}, {"percentage": "2.3E-5", "region": "Bucharest"}, {"percentage": "1.5E-5", "region": "Brăila County"}, {"percentage": "8.0E-6", "region": "Alba County"}, {"percentage": "1.5E-5", "region": "Western Province"}, {"percentage": "3.0E-5", "region": "Plateau State"}, {"percentage": "4.5E-5", "region": "Rift Valley Province"}, {"percentage": "2.3E-5", "region": "Nyanza Province"}, {"percentage": "4.5E-5", "region": "Eastern Province"}, {"percentage": "1.5E-5", "region": "Central Province"}, {"percentage": "1.5E-5", "region": "Sylhet Division"}, {"percentage": "8.0E-6", "region": "Rajshahi Division"}, {"percentage": "1.5E-5", "region": "Dhaka Division"}, {"percentage": "2.3E-5", "region": "Chittagong Division"}, {"percentage": "8.0E-6", "region": "Burgas Province"}, {"percentage": "3.8E-5", "region": "Rivers State"}, {"percentage": "3.0E-5", "region": "Zamboanga Peninsula"}, {"percentage": "8.0E-6", "region": "Riau Islands Province"}, {"percentage": "0.000113", "region": "Kentucky"}, {"percentage": "8.0E-6", "region": "Western Cape"}, {"percentage": "1.5E-5", "region": "Northern Ireland"}, {"percentage": "1.5E-5", "region": "Scotland"}, {"percentage": "8.0E-6", "region": "Santa Fe"}, {"percentage": "8.0E-6", "region": "Attica (region)"}, {"percentage": "2.3E-5", "region": "Västra Götaland County"}, {"percentage": "3.0E-5", "region": "Andalusia"}, {"percentage": "1.5E-5", "region": "Principality of Asturias"}, {"percentage": "1.5E-5", "region": "Timor-Leste"}, {"percentage": "3.0E-5", "region": "Equatoria"}, {"percentage": "2.3E-5", "region": "Mpumalanga"}, {"percentage": "3.0E-5", "region": "Chiang Rai"}, {"percentage": "8.0E-6", "region": "Tabuk Region"}, {"percentage": "1.5E-5", "region": "Al-Qassim Province"}, {"percentage": "1.5E-5", "region": "West Virginia"}, {"percentage": "5.3E-5", "region": "South Carolina"}, {"percentage": "8.0E-6", "region": "Rhode Island"}, {"percentage": "4.5E-5", "region": "Oklahoma"}, {"percentage": "5.3E-5", "region": "North Carolina"}, {"percentage": "7.5E-5", "region": "Missouri"}, {"percentage": "7.5E-5", "region": "Mississippi"}, {"percentage": "3.0E-5", "region": "Maine"}, {"percentage": "4.5E-5", "region": "Chiang Mai"}, {"percentage": "8.0E-6", "region": "Lampang"}, {"percentage": "8.3E-5", "region": "Banten"}, {"percentage": "1.5E-5", "region": "East Kalimantan"}, {"percentage": "8.0E-6", "region": "Gorontalo"}, {"percentage": "8.0E-6", "

In [9]:
df3 = pd.read_csv('../data/american-gas-association-040824.csv')

In [131]:
dfS = pd.DataFrame({'A': ['cheese', 'bread'],'B': ['john', 'jill'],'C': [[{'percentage': '0.000545', 'region': 'Idaho'}, {'percentage': '0.999455', 'region': 'Washington'}],[{'percentage': '5.9E-5', 'region': 'California'}, {'percentage': '0.000943', 'region': 'Idaho'}, {'percentage': '0.998998', 'region': 'Washington'}]] })

In [207]:
dfS

        A     B                                                  C
0  cheese  john  [{'percentage': '0.000545', 'region': 'Idaho'}...
1   bread  jill  [{'percentage': '5.9E-5', 'region': 'Californi...

In [104]:
pd.concat([df.explode('C').drop(['C'], axis=1),
           df.explode('C')['C'].apply(pd.Series)],
          axis=1)

        A     B percentage      region
0  cheese  john   0.000545       Idaho
0  cheese  john   0.999455  Washington
1   bread  jill     5.9E-5  California
1   bread  jill   0.000943       Idaho
1   bread  jill   0.998998  Washington

In [23]:
pd.concat([df3[0:20].explode('delivery_by_region').drop(['delivery_by_region'], axis=1),
           df3[0:20].explode('delivery_by_region')['delivery_by_region'].apply(pd.Series)],
          axis=1)

,Unnamed: 0,id,ad_delivery_start_time,ad_delivery_stop_time,ad_snapshot_url,bylines,demographic_distribution,publisher_platforms,ad_creative_bodies,ad_creative_link_captions,...,ad_creative_link_titles,page_name,page_id,impressions.lower_bound,impressions.upper_bound,spend.lower_bound,spend.upper_bound,ad_start_month,ad_start_year,0
0,0,335150496182609,2024-02-12,2024-02-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.304506', 'age': '45-54', 'g...","['facebook', 'instagram']","[""Parents do a lot for their families. Now Was...",['p2a.co'],...,"[""Don't let Washington interfere.""]",American Gas Association,140877979844,4000,4999,100,200,2,2024,"[{'percentage': '0.095216', 'region': 'Arizona..."
1,1,414172620991172,2024-02-12,2024-02-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000867', 'age': '55-64', 'g...","['facebook', 'instagram']",['Tell Washington: Americans deserve to choose...,['p2a.co'],...,['Sign up today.'],American Gas Association,140877979844,9000,9999,400,500,2,2024,"[{'percentage': '0.094672', 'region': 'Arizona..."
2,2,914862493282401,2024-02-12,2024-02-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000149', 'age': '35-44', 'g...","['facebook', 'instagram']",['You just bought a house. Now Washington want...,['p2a.co'],...,['Sign the petition.'],American Gas Association,140877979844,10000,14999,400,500,2,2024,"[{'percentage': '0.143751', 'region': 'Arizona..."
3,3,1581172015969531,2024-02-12,2024-02-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000653', 'age': '18-24', 'g...","['facebook', 'instagram']",['Tell Washington: Restricting choice is bad f...,['p2a.co'],...,['Sign up today.'],American Gas Association,140877979844,3000,3999,100,200,2,2024,"[{'percentage': '0.13141', 'region': 'Arizona'..."
4,4,408114561707810,2024-02-12,2024-02-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000851', 'age': '55-64', 'g...","['facebook', 'instagram']",['Tell Washington: Leave my appliance alone.\n...,['p2a.co'],...,['Sign the petition.'],American Gas Association,140877979844,10000,14999,300,400,2,2024,"[{'percentage': '0.124754', 'region': 'Arizona..."
5,5,1119649559173589,2024-01-22,2024-02-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000292', 'age': '45-54', 'g...","['facebook', 'instagram']",['Tell Washington: Americans deserve to choose...,['p2a.co'],...,['Sign up today.'],American Gas Association,140877979844,20000,24999,1000,1500,1,2024,"[{'percentage': '0.087673', 'region': 'Arizona..."
6,6,1114044429597598,2024-01-22,2024-02-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000232', 'age': '35-44', 'g...","['facebook', 'instagram']",['Tell Washington: Restricting choice is bad f...,['p2a.co'],...,['Sign up today.'],American Gas Association,140877979844,25000,29999,1500,2000,1,2024,"[{'percentage': '0.12668', 'region': 'Arizona'..."
7,7,1071540644166256,2024-01-22,2024-02-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000345', 'age': '45-54', 'g...","['facebook', 'instagram']",['Tell Washington: Leave my appliance alone.\n...,['p2a.co'],...,['Sign the petition.'],American Gas Association,140877979844,30000,34999,1000,1500,1,2024,"[{'percentage': '0.116424', 'region': 'Arizona..."
8,8,368142672605190,2024-01-22,2024-02-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '9.9E-5', 'age': '25-34', 'gen...","['facebook', 'instagram']",['You just bought a house. Now Washington want...,['p2a.co'],...,['Sign the petition.'],American Gas Association,140877979844,25000,29999,1000,1500,1,2024,"[{'percentage': '9.8E-5', 'region': 'Unknown'}..."
9,9,1820287728427323,2024-01-22,2024-02-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.024979', 'age': '25-34', 'g...","['facebook', 'instagram']","[""Parents do a lot for their families. Now Was...",['p2a.co'],...,"[""Don't let Washington interfere.""]",American Gas Association,140877979844,35000,39999,1500,2000,1,2024,"[{'percentage': '0.085935', 'region': 'Arizona..."
10,10,2306108322912625,2023-12-13,2024-01-16,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.156401', 'age': '45-54', 'g...","['facebook', 'instagram']","[""Parents do a lot for their families. Now Was...",['p2a.co'],...,"[""Don't let Washington interfere.""]",American Gas Association,140877979844,6000,6999,200,300,12,2023,"[{'percentage': '0.000327', 'region': 'Unknown..."
11,11,3229889257312282,2023-12-13,2024-01-16,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000179', 'age': '25-34', 'g...","['facebook', 'instagram']",['You just bought a house. Now Washington want...,['p2a.co'],...,['Sign the petition.'],American Gas Association,140877979844,15000,19999,200,300,12,2023,"[{'percentage': '0.000628', 'region': 'Hawaii'..."
12,12,338846262114843,2023-11-30,2024-01-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.162245', 'age': '35-44', 'g...","['facebook', 'instagram']","[""Parents do a lot for their families. Now Was...",['p2a.co'],...,"[""Don't let Washington interfere.""]",American Gas Association,140877979844,1000,1999,100,200,11,2023,"[{'percentage': '0.004069', 'region': 'Rhode I..."
13,13,1410561923190404,2023-11-30,2024-01-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.036437', 'age': '25-34', 'g...","['facebook', 'instagram']","[""Parents do a lot for their families. Now Was...",['p2a.co'],...,"[""Don't let Washington interfere.""]",American Gas Association,140877979844,0,999,0,100,11,2023,"[{'percentage': '0.004082', 'region': 'Rhode I..."
14,14,903932734406530,2023-11-30,2024-01-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.003928', 'age': '25-34', 'g...","['facebook', 'instagram']",['You just bought a house. Now Washington want...,['p2a.co'],...,['Sign the petition.'],American Gas Association,140877979844,2000,2999,0,100,11,2023,"[{'percentage': '0.000782', 'region': 'Alaska'..."
15,15,567614125533221,2023-11-30,2024-01-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.00463', 'age': '65+', 'gend...","['facebook', 'instagram']",['You just bought a house. Now Washington want...,['p2a.co'],...,['Sign the petition.'],American Gas Association,140877979844,0,999,0,100,11,2023,"[{'percentage': '0.00311', 'region': 'Mississi..."
16,16,1032560721318914,2023-11-30,2024-01-16,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000563', 'age': '18-24', 'g...","['facebook', 'instagram']",['Tell Washington: Restricting choice is bad f...,['p2a.co'],...,['Sign up today.'],American Gas Association,140877979844,4000,4999,100,200,11,2023,"[{'percentage': '0.001122', 'region': 'Alaska'..."
17,17,848333480374142,2023-11-30,2024-01-16,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000362', 'age': '25-34', 'g...","['facebook', 'instagram']",['Tell Washington: Restricting choice is bad f...,['p2a.co'],...,['Sign up today.'],American Gas Association,140877979844,7000,7999,200,300,11,2023,"[{'percentage': '0.003592', 'region': 'Alaska'..."
18,18,920939416291417,2023-11-30,2024-01-16,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '9.2E-5', 'age': '35-44', 'gen...","['facebook', 'instagram']",['Tell Washington: Americans deserve to choose...,['p2a.co'],...,['Sign up today.'],American Gas Association,140877979844,25000,29999,500,600,11,2023,"[{'percentage': '0.000556', 'region': 'Hawaii'..."
19,19,1041311360324328,2023-11-30,2024-01-15,https://www.facebook.com/ads/archive/render_ad...,American Gas Association,"[{'percentage': '0.000561', 'age': '45-54', 'g...","['facebook', 'instagram']",['Tell Washington: Americans deserve to choose...,['p2a.co'],...,['Sign up today.'],American Gas Association,140877979844,4000,4999,100,200,11,2023,"[{'percentage': '0.000563', 'region': 'Hawaii'..."

In [102]:
df[['id', 'ad_snapshot_url', 'page_id', 'delivery_by_region']].explode("delivery_by_region")["delivery_by_region"].apply(pd.Series)

                                                       0
0      [{'percentage': '0.000545', 'region': 'Idaho'}...
1      [{'percentage': '0.000434', 'region': 'Idaho'}...
2      [{'percentage': '0.00037', 'region': 'Idaho'},...
3          [{'percentage': '1', 'region': 'Washington'}]
4      [{'percentage': '0.00191', 'region': 'Idaho'},...
...                                                  ...
21030  [{'percentage': '0.030968', 'region': 'Alabama...
21031  [{'percentage': '0.064687', 'region': 'Alabama...
21032  [{'percentage': '0.032231', 'region': 'Alabama...
21033  [{'percentage': '0.069021', 'region': 'Alabama...
21034  [{'percentage': '0.033251', 'region': 'Alabama...

[21035 rows x 1 columns]

In [20]:
# export data
result[['page_name', 'region', 'lowerAmount', 'upperAmount', 'percentage']].query("percentage > 0.10").groupby(['page_name', 'region']).sum(['lowerAmount', 'upperAmount']).reset_index().rename(columns={'page_name':'name'}).to_json('../data/individual-040824.json', orient = 'records')